### PR TITLE
Create slides from slide master layouts

### LINKED ISSUE #16: Create new slides from slide master layout
I think it would also be valuable to be able to create a new slide from a slide master layout, and to be able to replace shapes with pictures as well (as picture placeholders are defined as `Shape` in the `ShapeTree`). I have a bit of code here that creates new slides from the master layout:

```
        public static void CreateNewSlideFromLayout(PresentationPart presentationPart, SlideAddCommand command)
        {
            Slide slide = new Slide();
            SlidePart slidePart = presentationPart.AddNewPart<SlidePart>();
            slide.Save(slidePart);

            SlideMasterPart slideMasterPart = presentationPart.SlideMasterParts.FirstOrDefault();
            SlideLayoutPart slideLayoutPart = slideMasterPart.SlideLayoutParts.SingleOrDefault(sl => sl.SlideLayout.CommonSlideData.Name.Value.Equals(command.LayoutName, StringComparison.OrdinalIgnoreCase));

            slidePart.AddPart(slideLayoutPart, slideMasterPart.GetIdOfPart(slideLayoutPart));
            slidePart.Slide.CommonSlideData = (CommonSlideData)slideLayoutPart.SlideLayout.CommonSlideData.Clone();

            string id = slideMasterPart.GetIdOfPart(slideLayoutPart);

            slideMasterPart.AddPart(slideLayoutPart, id);
            presentationPart.SetSlideID(slidePart, command.SlideNumber);
        }
```

Where SetSlideID is the following:

```
private static void SetSlideID(this PresentationPart presentationPart, SlidePart slidePart, int position = -1)
{
    SlideIdList slideIdList = presentationPart.Presentation.SlideIdList;
    if (slideIdList == null)
    {
        slideIdList = new SlideIdList();
        presentationPart.Presentation.SlideIdList = slideIdList;
    }


    if (position >= slideIdList.Count())
        throw new InvalidOperationException($"Unable to set slide to position '{position}'. There are only '{slideIdList.Count()}' slides.");

    uint newId = slideIdList.ChildElements.Count() == 0 ? 256 : slideIdList.GetMaxSlideId() + 1;
    if (position < 0)
    {
        var newSlideId = slideIdList.AppendChild(new SlideId());
        newSlideId.Id = newId;
        newSlideId.RelationshipId = presentationPart.GetIdOfPart(slidePart);
    }
    else if (slideIdList.Count() == 0)
    {
        var newSlideId = slideIdList.AppendChild(new SlideId());
        newSlideId.Id = newId;
        newSlideId.RelationshipId = presentationPart.GetIdOfPart(slidePart);
    }
    else
    {
        SlideId nextSlideId = (SlideId)slideIdList.ChildElements[position];
        var newSlideId = slideIdList.InsertBefore(new SlideId(), nextSlideId);
        newSlideId.Id = newId;
        newSlideId.RelationshipId = presentationPart.GetIdOfPart(slidePart);
    }
}

private static uint GetMaxSlideId(this SlideIdList slideIdList)
{
    uint maxSlideId = 0;
    if (slideIdList.ChildElements.Count() > 0)
        maxSlideId = slideIdList.ChildElements
            .Cast<SlideId>()
            .Max(x => x.Id.Value);
    return maxSlideId;
}
```

It needs a bit of tidying up (I think setting slide ID could be done better), but it's a good start

_Originally posted by @Tom-Kingstone in https://github.com/BHoM/PowerPoint_Toolkit/issues/15#issuecomment-2167416276_

### PR DESCRIPTION
**Pull request by Tom-Kingstone**
### Issues addressed by this PR

Closes #16 

As in the issue, added the ability to create new slides using templates from the slide master.

In order to make adding images to slides created from layouts work correctly, the ImageUpdate method has been updated so that any `Shape` elements can be converted into `Picture` elements. Original functionality is otherwise unchanged, and Picture elements can still be updated with images.

Utilised the `OpenXmlValidator` to allow users who may have used invalid inputs that aren't/couldn't be caught before updating to see that part of the update may not have worked correctly.

Created method that gets an element on a slide by its element name, and used it instead of getting it manually for every update method.

### Test files

[PowerPoint_Toolkit-16.zip](https://github.com/user-attachments/files/16800253/PowerPoint_Toolkit-16.zip)

### CODE REVIEW

**Comment by Tom-Kingstone** [comment]
@BHoMBot check core
@BHoMBot check compliance

**Comment by Tom-Kingstone** [comment]
@BHoMBot fix copyright headers ref. 29427643196

**Comment by Tom-Kingstone** [comment]
@BHoMBot check core
@BHoMBot check compliance

**Comment by Tom-Kingstone** [comment]
@BHoMBot check installer

**Comment by Tom-Kingstone** [comment]
@BHoMBot check null-handling
@BHoMBot check ready-to-merge

**Comment by charliebrookerBH** [comment]
Hey @adecler, @IsakNaslundBh - automated ppt outputs are next on our task list for the Box Model i project. Please would it be possible to get PPT TK merged soon (next couple of weeks?) so that we're able to fully utilise it?

**Comment by adecler** [comment]
Hey @charliebrookerBH. Yes, I am planning to review this next week at the latest. Sorry for the delay.

**Comment by adecler** [comment]
@BHoMBot check null-handling
@BHoMBot check serialisation

**Comment by adecler** [comment]
@BHoMBot check required

**Comment by adecler** [comment]
@BHoMBot check core

**Comment by adecler** [comment]
@BHomBot check compliance

**Comment by adecler** [comment]
@BHoMBot check required

**Review by adecler — APPROVED** [review]
- This provides the functionality discussed in the issue. I have tested it using the test file provided in the PR and all works well. 
 - I would suggest also adding the ability to create a new slide from an existing one as the ones provided in the master are very limited and too far from the final product. A good example of that would be the Floor Configurator where the same complex slide need to be duplicated a few times. This is outside of the scope of this PR however so I have raised a separate issue here: https://github.com/BHoM/PowerPoint_Toolkit/issues/29
 - I am generally happy with the code itself. I have just replaced the use of `Cast` with calls to `OfType` as the latter is more robust. I have done the same for the uses of `IsAssignableFrom` as that method is quite slow and was doing exactly what `OfType` is meant to do.
 - I have also update the assembly version to 8.0 to align with compliance requirements.

**Comment by adecler** [comment]
@BHoMBot check ready-to-merge

**Pull request merged**
