### PR TITLE
Add nuspec file

### LINKED ISSUE #6: Add nuspec file
To prepare this repository for being a nuget, add the nuspec file after #5 is merged.

FYI @adecler

### PR DESCRIPTION
**Pull request by FraserGreenroyd**
Fixes #6

### CODE REVIEW

**Comment by FraserGreenroyd** [comment]
@BHoMBot check core -force

**Comment by FraserGreenroyd** [comment]
@BHoMBot check core

**Comment by FraserGreenroyd** [comment]
@BHoMBot check core

**Comment by FraserGreenroyd** [comment]
@BHoMBot check compliance
@BHoMBot check required

**Comment by FraserGreenroyd** [comment]
@BHoMBot fix project file ref. 18443426437

**Comment by FraserGreenroyd** [comment]
@BHoMBot check compliance

**Comment by FraserGreenroyd** [comment]
@BHoMBot check installer
@BHoMBot check null-handling
@BHoMBot check core
@BHoMBot check serialisation

**Review by Tom-Kingstone — APPROVED** [review]
nuspec file looks good. Approved.

**Comment by FraserGreenroyd** [comment]
@BHoMBot check ready-to-merge

**Pull request merged**
